# Generated by Django 2.1.5 on 2019-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField()),
                ('cost', models.IntegerField(default=0)),
                ('money_use', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', '食費'), ('fare', '交通費'), ('medical', '医療費'), ('tuition', '学費'), ('amusement', '娯楽費'), ('tax', '税金'), ('communication', '通信費'), ('clothes', '衣料品'), ('others', '雑費')], max_length=10)),
            ],
        ),
    ]
