# Generated by Django 2.1.5 on 2019-03-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0002_receiptimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptimage',
            name='img_thumbnail',
        ),
        migrations.AddField(
            model_name='receiptimage',
            name='img',
            field=models.ImageField(default='test', upload_to='receipt'),
            preserve_default=False,
        ),
    ]
